apiVersion: apps/v1
kind: DaemonSet
metadata:
   name: httpdaemon
spec:
   selector:
      matchLabels:
          name: httpdaemon
   template:
      metadata:
          labels:
           name: httpdaemon
      spec:
        containers:
        - name: httpd
          image: httpd
          ports:
          - containerPort: 80
