apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
     kubernetes.io/change-cause: kubectl run mydep --image=ghost:0.9 --record=true --dry-run=true --output=yaml
  creationTimestamp: null
  labels:
    app: mydep1
  name: mydep1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydep1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mydep1
    spec:
      containers:
      - image: ghost:0.9
        name: ghost
        resources: {}
status: {}
