apiVersion: apps/v1
kind: Deployment
metadata: 
  name: httpd-deployment
  namespace: gunjan
spec: 
  selector:
     matchLabels:
       app: httpd-deployment
  replicas: 1 
  template: 
     metadata: 
        labels:
          app: httpd-deployment
     spec:
       containers:
       - name: httpd
         image: docker.io/httpd
         ports:
         - containerPort: 80
