apiVersion: v1
kind: Pod
metadata:
  name: initpod-1
  labels:
    app: initpod 
spec:
  containers:
  - name: initpod-container
    image: registry.access.redhat.com/ubi8/ubi
    command: ['sh','-c','echo The app is running && sleep 3600']
  initContainers:
  - name: init-service1
    image: registry.access.redhat.com/ubi8/ubi
    command: ['sh','-c',"until getent hosts service1; do echo waiting for service1; sleep 2; done"]
  - name: init-data1
    image: registry.access.redhat.com/ubi8/ubi
    command: ['sh','-c',"until getent hosts data1; do echo waiting for data1; sleep 2; done"]

