apiVersion: v1
kind: Pod
metadata: 
  name: mysql1
spec: 
  containers:
  - name: mysql
    image: docker.io/mysql
    env:
      - name: "MYSQL_USER"
        value: "mysql"
      - name: "MYSQL_PASSWORD"
        value: "mysql"
      - name: "MYSQL_DATABASE"
        value: "cka"
      - name: "MYSQL_ROOT_PASSWORD"
        value: "redhat"
    ports:
        - containerPort: 3306
