apiVersion: v1
kind: Pod
metadata: 
  name: httpd-node
spec:
  affinity:
    nodeAffinity:
       preferredDuringSchedulingIgnoredDuringExecution:
       - weight: 1
         preference:
            matchExpressions:
            - key: color
              operator: NotIn
              values:
              - black
  containers:
  - name: httpd
    image: docker.io/httpd
