apiVersion: v1
kind: Pod
metadata:
  name: postgres2
spec:
  containers:
  - name: psql
    image: docker.io/postgres
    env:
      - name: "POSTGRES_USER"
        value: "postgres"
      - name: "POSTGRES_PASSWORD"
        value: "postgres"
      - name: "POSTGRES_DB"
        value: "pgdb"
    ports:
      - containerPort: 3307
