apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: psql
  name: psql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: psql
    spec:
      containers:
      - image: postgres
        name: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: redhat
        - name: POSTGRES_DB
          value: pgdb1
        resources: {}
status: {}
