apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: replicatest1
   labels:
     app: replicaset
     tier: frontend
spec:
  replicas: 3
  selector:
     matchLabels:
          tier: frontend
  template:
     metadata:
         labels:
            tier: frontend
     spec:
       containers:
       - name: redis
         image: gcr.io/google_samples/gb-frontend:v3
